version: '3.9'
services:

  web:
    build: ./
    environment:
     - WATCHPACK_POLLING=true
    volumes:
      - ./:/app
    command: sh -c "yarn && yarn dev"
    tty: true
    stdin_open: true
    ports:
    - "3000:3000"
